<?php

use App\PropertyAnalytic;
use Illuminate\Database\Seeder;

class PropertyAnalyticsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $propertyAnalytics = [
            [
                'property_id'      => 1,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 2,
                'analytic_type_id' => 1,
                'value'            => 21,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 3,
                'analytic_type_id' => 1,
                'value'            => 29,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 4,
                'analytic_type_id' => 1,
                'value'            => 16,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 5,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 6,
                'analytic_type_id' => 1,
                'value'            => 15,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 7,
                'analytic_type_id' => 1,
                'value'            => 21,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 8,
                'analytic_type_id' => 1,
                'value'            => 10,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 9,
                'analytic_type_id' => 1,
                'value'            => 14,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 10,
                'analytic_type_id' => 1,
                'value'            => 24,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 11,
                'analytic_type_id' => 1,
                'value'            => 26,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 12,
                'analytic_type_id' => 1,
                'value'            => 12,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 13,
                'analytic_type_id' => 1,
                'value'            => 22,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 14,
                'analytic_type_id' => 1,
                'value'            => 22,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 15,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 16,
                'analytic_type_id' => 1,
                'value'            => 10,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 17,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 18,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 19,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 20,
                'analytic_type_id' => 1,
                'value'            => 28,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 21,
                'analytic_type_id' => 1,
                'value'            => 11,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 22,
                'analytic_type_id' => 1,
                'value'            => 22,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 23,
                'analytic_type_id' => 1,
                'value'            => 30,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 24,
                'analytic_type_id' => 1,
                'value'            => 11,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 25,
                'analytic_type_id' => 1,
                'value'            => 35,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 26,
                'analytic_type_id' => 1,
                'value'            => 11,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 27,
                'analytic_type_id' => 1,
                'value'            => 37,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 28,
                'analytic_type_id' => 1,
                'value'            => 13,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 29,
                'analytic_type_id' => 1,
                'value'            => 38,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 30,
                'analytic_type_id' => 1,
                'value'            => 29,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 31,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 32,
                'analytic_type_id' => 1,
                'value'            => 28,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 33,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 34,
                'analytic_type_id' => 1,
                'value'            => 11,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 35,
                'analytic_type_id' => 1,
                'value'            => 12,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 36,
                'analytic_type_id' => 1,
                'value'            => 20,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 37,
                'analytic_type_id' => 1,
                'value'            => 39,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 38,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 39,
                'analytic_type_id' => 1,
                'value'            => 35,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 40,
                'analytic_type_id' => 1,
                'value'            => 28,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 41,
                'analytic_type_id' => 1,
                'value'            => 31,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 42,
                'analytic_type_id' => 1,
                'value'            => 19,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 43,
                'analytic_type_id' => 1,
                'value'            => 13,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 44,
                'analytic_type_id' => 1,
                'value'            => 25,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 45,
                'analytic_type_id' => 1,
                'value'            => 39,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 46,
                'analytic_type_id' => 1,
                'value'            => 22,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 47,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 48,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 49,
                'analytic_type_id' => 1,
                'value'            => 27,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 50,
                'analytic_type_id' => 1,
                'value'            => 25,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 51,
                'analytic_type_id' => 1,
                'value'            => 39,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 52,
                'analytic_type_id' => 1,
                'value'            => 20,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 53,
                'analytic_type_id' => 1,
                'value'            => 23,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 54,
                'analytic_type_id' => 1,
                'value'            => 15,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 55,
                'analytic_type_id' => 1,
                'value'            => 39,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 56,
                'analytic_type_id' => 1,
                'value'            => 27,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 57,
                'analytic_type_id' => 1,
                'value'            => 36,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 58,
                'analytic_type_id' => 1,
                'value'            => 31,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 59,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 60,
                'analytic_type_id' => 1,
                'value'            => 33,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 61,
                'analytic_type_id' => 1,
                'value'            => 14,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 62,
                'analytic_type_id' => 1,
                'value'            => 13,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 63,
                'analytic_type_id' => 1,
                'value'            => 26,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 64,
                'analytic_type_id' => 1,
                'value'            => 10,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 65,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 66,
                'analytic_type_id' => 1,
                'value'            => 23,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 67,
                'analytic_type_id' => 1,
                'value'            => 16,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 68,
                'analytic_type_id' => 1,
                'value'            => 18,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 69,
                'analytic_type_id' => 1,
                'value'            => 15,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 70,
                'analytic_type_id' => 1,
                'value'            => 18,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 71,
                'analytic_type_id' => 1,
                'value'            => 18,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 72,
                'analytic_type_id' => 1,
                'value'            => 23,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 73,
                'analytic_type_id' => 1,
                'value'            => 36,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 74,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 75,
                'analytic_type_id' => 1,
                'value'            => 23,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 76,
                'analytic_type_id' => 1,
                'value'            => 29,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 77,
                'analytic_type_id' => 1,
                'value'            => 32,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 78,
                'analytic_type_id' => 1,
                'value'            => 33,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 79,
                'analytic_type_id' => 1,
                'value'            => 36,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 80,
                'analytic_type_id' => 1,
                'value'            => 37,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 81,
                'analytic_type_id' => 1,
                'value'            => 22,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 82,
                'analytic_type_id' => 1,
                'value'            => 12,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 83,
                'analytic_type_id' => 1,
                'value'            => 16,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 84,
                'analytic_type_id' => 1,
                'value'            => 9,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 85,
                'analytic_type_id' => 1,
                'value'            => 9,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 86,
                'analytic_type_id' => 1,
                'value'            => 20,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 87,
                'analytic_type_id' => 1,
                'value'            => 14,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 88,
                'analytic_type_id' => 1,
                'value'            => 15,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 89,
                'analytic_type_id' => 1,
                'value'            => 17,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 90,
                'analytic_type_id' => 1,
                'value'            => 15,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 91,
                'analytic_type_id' => 1,
                'value'            => 10,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 92,
                'analytic_type_id' => 1,
                'value'            => 22,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 93,
                'analytic_type_id' => 1,
                'value'            => 21,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 94,
                'analytic_type_id' => 1,
                'value'            => 16,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 95,
                'analytic_type_id' => 1,
                'value'            => 11,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 96,
                'analytic_type_id' => 1,
                'value'            => 33,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 97,
                'analytic_type_id' => 1,
                'value'            => 36,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 98,
                'analytic_type_id' => 1,
                'value'            => 34,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 99,
                'analytic_type_id' => 1,
                'value'            => 13,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 100,
                'analytic_type_id' => 1,
                'value'            => 33,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 2,
                'analytic_type_id' => 2,
                'value'            => 340,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 3,
                'analytic_type_id' => 2,
                'value'            => 823,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 4,
                'analytic_type_id' => 2,
                'value'            => 821,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 6,
                'analytic_type_id' => 2,
                'value'            => 1095,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 8,
                'analytic_type_id' => 2,
                'value'            => 1101,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 9,
                'analytic_type_id' => 2,
                'value'            => 970,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 10,
                'analytic_type_id' => 2,
                'value'            => 1049,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 12,
                'analytic_type_id' => 2,
                'value'            => 184,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 14,
                'analytic_type_id' => 2,
                'value'            => 192,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 15,
                'analytic_type_id' => 2,
                'value'            => 939,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 16,
                'analytic_type_id' => 2,
                'value'            => 745,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 18,
                'analytic_type_id' => 2,
                'value'            => 749,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 20,
                'analytic_type_id' => 2,
                'value'            => 428,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 21,
                'analytic_type_id' => 2,
                'value'            => 277,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 22,
                'analytic_type_id' => 2,
                'value'            => 1103,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 24,
                'analytic_type_id' => 2,
                'value'            => 544,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 26,
                'analytic_type_id' => 2,
                'value'            => 778,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 27,
                'analytic_type_id' => 2,
                'value'            => 234,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 28,
                'analytic_type_id' => 2,
                'value'            => 395,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 30,
                'analytic_type_id' => 2,
                'value'            => 784,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 32,
                'analytic_type_id' => 2,
                'value'            => 247,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 33,
                'analytic_type_id' => 2,
                'value'            => 959,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 34,
                'analytic_type_id' => 2,
                'value'            => 738,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 36,
                'analytic_type_id' => 2,
                'value'            => 559,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 38,
                'analytic_type_id' => 2,
                'value'            => 599,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 39,
                'analytic_type_id' => 2,
                'value'            => 383,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 40,
                'analytic_type_id' => 2,
                'value'            => 282,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 42,
                'analytic_type_id' => 2,
                'value'            => 309,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 44,
                'analytic_type_id' => 2,
                'value'            => 410,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 45,
                'analytic_type_id' => 2,
                'value'            => 190,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 46,
                'analytic_type_id' => 2,
                'value'            => 594,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 48,
                'analytic_type_id' => 2,
                'value'            => 228,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 50,
                'analytic_type_id' => 2,
                'value'            => 284,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 51,
                'analytic_type_id' => 2,
                'value'            => 758,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 52,
                'analytic_type_id' => 2,
                'value'            => 503,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 54,
                'analytic_type_id' => 2,
                'value'            => 672,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 56,
                'analytic_type_id' => 2,
                'value'            => 714,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 57,
                'analytic_type_id' => 2,
                'value'            => 896,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 58,
                'analytic_type_id' => 2,
                'value'            => 801,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 60,
                'analytic_type_id' => 2,
                'value'            => 1067,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 62,
                'analytic_type_id' => 2,
                'value'            => 1016,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 63,
                'analytic_type_id' => 2,
                'value'            => 918,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 64,
                'analytic_type_id' => 2,
                'value'            => 535,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 66,
                'analytic_type_id' => 2,
                'value'            => 970,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 68,
                'analytic_type_id' => 2,
                'value'            => 1004,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 69,
                'analytic_type_id' => 2,
                'value'            => 238,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 70,
                'analytic_type_id' => 2,
                'value'            => 296,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 72,
                'analytic_type_id' => 2,
                'value'            => 663,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 74,
                'analytic_type_id' => 2,
                'value'            => 1034,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 75,
                'analytic_type_id' => 2,
                'value'            => 318,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 76,
                'analytic_type_id' => 2,
                'value'            => 301,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 78,
                'analytic_type_id' => 2,
                'value'            => 779,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 80,
                'analytic_type_id' => 2,
                'value'            => 225,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 81,
                'analytic_type_id' => 2,
                'value'            => 839,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 82,
                'analytic_type_id' => 2,
                'value'            => 349,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 84,
                'analytic_type_id' => 2,
                'value'            => 567,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 86,
                'analytic_type_id' => 2,
                'value'            => 430,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 87,
                'analytic_type_id' => 2,
                'value'            => 626,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 88,
                'analytic_type_id' => 2,
                'value'            => 812,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 90,
                'analytic_type_id' => 2,
                'value'            => 960,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 92,
                'analytic_type_id' => 2,
                'value'            => 815,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 93,
                'analytic_type_id' => 2,
                'value'            => 1078,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 94,
                'analytic_type_id' => 2,
                'value'            => 605,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 96,
                'analytic_type_id' => 2,
                'value'            => 313,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 98,
                'analytic_type_id' => 2,
                'value'            => 716,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 99,
                'analytic_type_id' => 2,
                'value'            => 426,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 100,
                'analytic_type_id' => 2,
                'value'            => 577,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 2,
                'analytic_type_id' => 3,
                'value'            => 1.270018421451,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 4,
                'analytic_type_id' => 3,
                'value'            => 3.02554390425922,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 6,
                'analytic_type_id' => 3,
                'value'            => 2.63667691804908,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 8,
                'analytic_type_id' => 3,
                'value'            => 3.34638761383774,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 10,
                'analytic_type_id' => 3,
                'value'            => 2.85946874448447,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 12,
                'analytic_type_id' => 3,
                'value'            => 1.07455818832434,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 14,
                'analytic_type_id' => 3,
                'value'            => 2.93233884099814,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 16,
                'analytic_type_id' => 3,
                'value'            => 2.08758436325617,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 18,
                'analytic_type_id' => 3,
                'value'            => 3.40851708259508,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 20,
                'analytic_type_id' => 3,
                'value'            => 0.861759136359483,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 22,
                'analytic_type_id' => 3,
                'value'            => 1.54152511679388,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 24,
                'analytic_type_id' => 3,
                'value'            => 3.29812705399504,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 26,
                'analytic_type_id' => 3,
                'value'            => 1.22639999511863,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 28,
                'analytic_type_id' => 3,
                'value'            => 1.86537956497071,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 30,
                'analytic_type_id' => 3,
                'value'            => 3.17141275022874,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 32,
                'analytic_type_id' => 3,
                'value'            => 2.03504700401259,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 34,
                'analytic_type_id' => 3,
                'value'            => 2.09978462447799,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 36,
                'analytic_type_id' => 3,
                'value'            => 1.94359942478887,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 38,
                'analytic_type_id' => 3,
                'value'            => 0.719948632353141,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 40,
                'analytic_type_id' => 3,
                'value'            => 2.55339132447577,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 42,
                'analytic_type_id' => 3,
                'value'            => 1.74514087354835,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 44,
                'analytic_type_id' => 3,
                'value'            => 2.52377120121313,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 46,
                'analytic_type_id' => 3,
                'value'            => 3.33205801613017,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 48,
                'analytic_type_id' => 3,
                'value'            => 1.81493301369798,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 50,
                'analytic_type_id' => 3,
                'value'            => 2.354128601899,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 52,
                'analytic_type_id' => 3,
                'value'            => 1.29475594364735,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 54,
                'analytic_type_id' => 3,
                'value'            => 2.00803578247901,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 56,
                'analytic_type_id' => 3,
                'value'            => 1.99181645854951,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 58,
                'analytic_type_id' => 3,
                'value'            => 1.38718701818959,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 60,
                'analytic_type_id' => 3,
                'value'            => 3.41210137589376,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 62,
                'analytic_type_id' => 3,
                'value'            => 2.10143755360922,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 64,
                'analytic_type_id' => 3,
                'value'            => 1.69779214431758,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 66,
                'analytic_type_id' => 3,
                'value'            => 1.07272036989671,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 68,
                'analytic_type_id' => 3,
                'value'            => 1.89646034528337,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 70,
                'analytic_type_id' => 3,
                'value'            => 1.59923758014031,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 72,
                'analytic_type_id' => 3,
                'value'            => 2.24741182410057,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 74,
                'analytic_type_id' => 3,
                'value'            => 1.85165334715295,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 76,
                'analytic_type_id' => 3,
                'value'            => 2.29043534100455,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 78,
                'analytic_type_id' => 3,
                'value'            => 3.17278354166389,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 80,
                'analytic_type_id' => 3,
                'value'            => 1.5301314232142,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 82,
                'analytic_type_id' => 3,
                'value'            => 2.03650137252948,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 84,
                'analytic_type_id' => 3,
                'value'            => 0.628650031117029,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 86,
                'analytic_type_id' => 3,
                'value'            => 0.961903239505828,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 88,
                'analytic_type_id' => 3,
                'value'            => 2.70683468642116,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 90,
                'analytic_type_id' => 3,
                'value'            => 0.740960349788634,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 92,
                'analytic_type_id' => 3,
                'value'            => 0.722688917506204,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 94,
                'analytic_type_id' => 3,
                'value'            => 1.34368791736724,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 96,
                'analytic_type_id' => 3,
                'value'            => 2.43551453556817,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 98,
                'analytic_type_id' => 3,
                'value'            => 2.5791942343968,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
            [
                'property_id'      => 100,
                'analytic_type_id' => 3,
                'value'            => 2.50976993268386,
                'created_at'       => now(),
                'updated_at'       => now(),
            ],
        ];

        PropertyAnalytic::insert($propertyAnalytics);
    }
}
